# Generated by Django 5.1.6 on 2025-04-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='title',
        ),
    ]
