# Generated by Django 5.1.6 on 2025-04-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0002_rename_name_destination_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='desc',
            new_name='designation',
        ),
    ]
