# Generated by Django 5.1.6 on 2025-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0003_rename_desc_destination_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('full_name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=70)),
                ('designation', models.TextField()),
            ],
        ),
    ]
