# Generated by Django 5.1.6 on 2025-05-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('tree', 'Tree Felling')], default='plumbing', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='plumbing_image',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tree_feeling',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('tree', 'Tree Felling')], default='plumbing', max_length=20),
        ),
    ]
