
services:
  - type: web
    name: courage-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn courage.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: your-django-secret-key-here
      - key: DATABASE_URL
        fromDatabase:
          name: courage-db
          property: connectionString

databases:
  - name: courage-db
    plan: free
    databaseName: karjo
    user: postgres


