# Generated by Django 5.1.6 on 2025-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('select_service', models.TextField()),
                ('date', models.DateField()),
                ('special_request', models.TextField()),
            ],
        ),
    ]
