# Generated by Django 5.1.6 on 2025-04-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='phone_number',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.TextField(),
        ),
    ]
