# Generated by Django 5.1.6 on 2025-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_bookings_phone_number_alter_bookings_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='bookings',
            name='phonenumber',
            field=models.CharField(default=2, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='select_service',
            field=models.CharField(choices=[('Drain_cleaning', 'Drain_cleaning'), ('Sewer_line', 'Sewer_line'), ('Water_heating', 'Water_heating'), ('Toilet_cleaning', 'Toilet_cleaning'), ('Broken_Pipe', 'Broken_Pipe')], max_length=50),
        ),
    ]
