# Generated by Django 5.1.6 on 2025-04-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='names',
        ),
    ]
